name: "Software, Science, and Stuff"

description: "Personal and Professional Website of Eric Appelt"

author: Eric Appelt

author_email: eric.appelt@gmail.com

markdown: kramdown
highlighter: rouge

collections:
  - sections

exclude:
  - README.md
  - "*.py"
  - venv
